#! /bin/sh
# /etc/init.d/mjpg_streamkick Carry out specific functions when asked to 
# by the system
case "$1" in
  start)
    echo "Starting mjpg_streamkick script"
    #export LD_LIBRARY_PATH=/usr/local/bin
    #mjpg_streamer -i "/usr/lib/input_uvc.so -d /dev/video0 -y -r 640x480 
#-q 95 -f 4 -l auto" -o "/usr/lib/output_http.so -p 8080 -w /usr/local/www 
#-c user:id" &
    LD_LIBRARY_PATH=/usr/local/lib mjpg_streamer -i "/usr/local/lib/input_uvc.so -y" -o "/usr/local/lib/output_http.so -w /usr/local/www"
    ;;
  stop)
    echo "Stopping webcam script"
    killall mjpg_streamer
    ;;
  *)
    echo "Usage: /etc/init.d/mjpg_streamkick {start|stop}"
    exit 1
    ;; esac
exit 0
